### ISSUE TITLE
Last gmod update broke addon

### ISSUE THREAD

**Issue by 00875** [Scentus/PonyPlayerModels#4]
Trying to debug cache.lua
![2015-06-05_15-20_garry s mod](https://cloud.githubusercontent.com/assets/6339511/8002134/846faf24-0b96-11e5-8011-c852b10cc097.jpg)
There is not any net.Send()
Last gmod update 'fixes' net.Send()
![2015-06-05_15-25_garry s mod](https://cloud.githubusercontent.com/assets/6339511/8002199/0d0fa5b4-0b97-11e5-9f37-73205bb23907.jpg)

**Comment by edgaraxe** [comment]
I will contact sentus.

**Comment by Scentus** [comment]
I'm aware of this issue and was going to look into it on Saturday (as announced on the addon page in the comments). Thank you for giving me a starting point in tracking down the issue though.

**Comment by ChristinaTech** [comment]
Issue is fixed in latest commit, was timer code that was broken by the latest update.
